### ISSUE TITLE
MQTT5 topic needs full sink and source address for uE-2-uE communication

### ISSUE THREAD

**Issue by stevenhartley** [eclipse-uprotocol/up-transport-mqtt5-java#3]
The issue is in the code below in https://github.com/eclipse-uprotocol/up-transport-mqtt5-java/pull/2/files#diff-195212d67a35823ba725c56231022575dcf19f0a530bc367b9063f3fcf2b1702R63:
````
.add(USER_PROPERTIES_KEY_FOR_SINK_NAME, uMessage.getAttributes().getSink().getAuthorityName())
.add(USER_PROPERTIES_KEY_FOR_PRIORITY, Integer.toString(uMessage.getAttributes().getPriorityValue()))
`````````````

It needs use the full serialized URI of the source and sink using `UriSerializer`

**Comment by r-vanooyen** [comment]
done
